# Generated by Django 4.2.7 on 2023-11-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('file_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('file_size', models.PositiveIntegerField()),
                ('word_count', models.PositiveIntegerField()),
            ],
        ),
    ]
