# Generated by Django 4.2.7 on 2023-11-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='word_count',
            field=models.BigIntegerField(),
        ),
    ]
