# Generated by Django 4.2.7 on 2023-11-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_file_alter_comment_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='word_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
