# Generated by Django 4.2.7 on 2023-11-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_file_name_alter_comment_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(blank=True, max_length=300, primary_key=True, serialize=False),
        ),
    ]
