# Generated by Django 4.2.8 on 2023-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0004_alter_comment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="doc_id",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
