# Generated by Django 4.2.8 on 2023-12-06 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0005_comment_doc_id_alter_comment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="doc_id",
        ),
    ]
