# Generated by Django 4.2.8 on 2023-12-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0006_remove_comment_doc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.CharField(
                blank=True, max_length=300, primary_key=True, serialize=False
            ),
        ),
    ]
