# Generated by Django 4.2.8 on 2023-12-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0007_alter_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.CharField(
                blank=True, max_length=19, primary_key=True, serialize=False
            ),
        ),
    ]
